env:
  map_xy_m: [320.0, 320.0]
  horizon_steps: 300
  dt_s: 1.0

  num_agents: 6
  num_tasks_total: 10
  num_users_total: 10

  task_spawn_schedule:
    spawn_fracs: [0.3, 0.5, 0.7]
    spawn_counts: [2, 2, 2]
  user_spawn_schedule:
    spawn_fracs: [0.3, 0.5, 0.7]
    spawn_counts: [2, 2, 2]

  sensing:
    visit_radius_m: 5.0
    dwell_steps: 7
    bytes_per_update: 700
    update_period_steps: 12
  users:
    cov_radius_m: 20.0
    bytes_per_step: 500
    speed_mps: 0.5

  comm:
    comm_range_m: 45.0
    base_pos_xy: [150.0, 150.0]
    base_range_m: 16.0
    link_capacity_bytes_per_step: 700
    buffer_bytes_max: 2500

  motion:
    v_max_mps: 3.5

  energy:
    e0_j: 4500.0
    move_cost_j_per_m: 3.0
    sense_cost_j_per_step: 5.0
    tx_cost_j_per_byte: 0.004
    low_energy_j: 600.0
