env:
  map_xy_m: [220.0, 220.0]
  horizon_steps: 300
  dt_s: 1.0

  num_agents: 6
  num_tasks_total: 10
  num_users_total: 0

  task_spawn_schedule:
    spawn_fracs: [0.3, 0.5, 0.7]
    spawn_counts: [2, 2, 2]
  user_spawn_schedule:
    spawn_fracs: [0.3, 0.5, 0.7]
    spawn_counts: [0, 0, 0]

  sensing:
    visit_radius_m: 18.0
    dwell_steps: 3
    bytes_per_update: 700
    update_period_steps: 12
  users:
    cov_radius_m: 25.0
    bytes_per_step: 500
    speed_mps: 0.5

  comm:
    comm_range_m: 70.0
    base_pos_xy: [110.0, 110.0]
    base_range_m: 34.0
    link_capacity_bytes_per_step: 700
    buffer_bytes_max: 2000

  motion:
    v_max_mps: 4.0

  energy:
    e0_j: 4200.0
    move_cost_j_per_m: 3.0
    sense_cost_j_per_step: 5.0
    tx_cost_j_per_byte: 0.004
    low_energy_j: 600.0
